name: Node CI

on:
  push:
    branches:
      - develop

jobs:

  install_test_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install
      run: npm install

    - name: npm run unit
      run: |
        echo "${{ secrets.priv }}" > src/config/priv.js
        npm run unit

    - name: npm run build
      run: |
        echo "${{ secrets.privBuild }}" > src/config/priv.js
        npm run build