name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: create apiKeys.js
      run: echo '${{ secrets.apiKeys }}' > src/config/apiKeys.js
    - name: npm install
      run: npm install
    - name: npm run unit
      run: npm run unit
    - name: npm run build
      run: npm run build