name: Node CI

on: [push]

jobs:

  install_test_build_upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
    - name: priv.js for testing
      run: echo "${{ secrets.priv }}" > src/config/priv.js
    - name: npm run unit
      run: npm run unit
    - name: priv.js for production
      run: echo "${{ secrets.privBuild }}" > src/config/priv.js
    - name: npm run build
      run: npm run build
    - name: upload build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: dist


  download_deploy:

    needs: install_test_build_upload
    runs-on: ubuntu-latest

    steps:
    - name: download build
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: ftp deploy
      uses: sfmiller940/ftp-action@master
      with:
        host: ${{ secrets.FTP_HOST}}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "build/dist"
        remoteDir: ${{ secrets.FTP_DIR }}