name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 'latest'
    - name: npm install
      run: npm install
    - name: npm run unit
      env:
        CI: true
        apiKeys: ${{ secrets.apiKeys }}
      run: npm run unit
    - name: npm run build
      env:
        CI: true
        apiKeys: ${{ secrets.apiKeys }}
      run: npm run build